[package]
name = "list_commits_action"
description = "Generate the list of commits from an event (push or PR)"
version = "0.1.0"

edition = "2021"

[dependencies]
ghactions = { version = "^0.9", features = ["generate"] }
anyhow = "1"
log = "0.4"
