name: CI Checks

on:
  push:
    branches-ignore: ["wip*"]
  pull_request:

jobs:
  check-conventional-commits:
    name: Check Conventional Commits
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.3.0

  code-checks:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - uses: actions/checkout@v4

      - name: "Cargo formatting"
        if: $${{ always() }}
        run: cargo fmt --all -- --check

      - name: "Cargo clippy"
        if: $${{ always() }}
        run: cargo clippy --profile=test --locked
